### ISSUE TITLE
Weather Underground API is sunsetting 2019-02-15, need to evaluate consequences for Freezing Saddles weather integrations

### ISSUE THREAD

**Issue by obscurerichard** [freezingsaddles/freezing-sync#5]
It looks like the Weather Underground API is sunsetting at the end of 2018, making it useless for the 2019 competition, alas: https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api

I haven't looked deep enough to see whether the https://github.com/freezingsaddles/freezing-sync/tree/master/freezing/sync/wx/ncdc code would offer enough weather information to be usable for this app yet.

Other alternatives that look promising are:
* https://darksky.net/dev
*  https://openweathermap.org/api

**Comment by obscurerichard** [comment]
Looks like they haven't shut off the API quite yet, but we still need to move. The https://darksky.net/dev API is looking better than the openweathermap.org one since it has some historical weather info available and a 1000 call per day free tier.

**Comment by obscurerichard** [comment]
The powers that be at IBM extended the API lifetime until Feb 15, 2019: https://apicommunity.wunderground.com/weatherapi/topics/weather-underground-api-update

**Comment by obscurerichard** [comment]
Additionally they _say_ there will be a new low-volume API available, but the details are not released yet: https://apicommunity.wunderground.com/weatherapi/topics/details-for-non-commercial-low-call-volume-api

I say we don't hold our breath and we start working on a Darky Sky integration.

**Comment by obscurerichard** [comment]
They cut it off hard on Feb 15, 2019, so now we *really* need to move to something else.

**Comment by spfrantz** [comment]
After looking at the NWS API, Dark Sky, and Open Weather Map, I agree that Dark Sky is the most promising. I'd be glad to help with this.
