### ISSUE TITLE
Triage MySQL 8 geospatial query compatibility with freezing-sync

### ISSUE THREAD

**Issue by obscurerichard** [freezingsaddles/freezing-sync#56]
In [Exception in all/tracks.geojson - suspected MySQL 8 incompatibility with SQLAlchemy #295](https://github.com/freezingsaddles/freezing-web/issues/295) @obscurerichard found a troubling exception that might require a whole chain of library upgrades to resolve. In https://github.com/freezingsaddles/freezing-web/issues/281 we upgraded to MySQL 8, but maybe without adequate testing.

We should triage `freezing-sync` to ensure that it does not run into trouble with`pymysql.err.OperationalError: (1305, 'FUNCTION freezing.AsBinary does not exist')` or similar error messages. The same references and leads that apply to https://github.com/freezingsaddles/freezing-web/issues/295 will likely apply here. The TLDR is that if we _do_ have a problem it might require us to upgrade or patch SQLAlchemy and friends, which is likely to be a **huge pain**.

### Integration testing
We could establish some integration tests that inject data into freezing-sync, possibly via beanstalkd messages, maybe with real live data from Strava, that can help us verify that ingesting Strava activities, including their tracks, is still working properly.

This is high effort, but low risk.

### Live testing
We could alter the start and end dates of the competition to temporarily have activities recorded from Strava get recorded, then clear them out of the database by doing a partial reset of the rides.

This is low effort, but medium risk and might be confusing to users.

**Comment by merlinorg** [comment]
So you can `sync_activities` locally without a lot of effort, which should exercise all the sync-related geo code. My notes for doing this are on an archived laptop but I think it's just a case of grabbing a key and rider id.

**Comment by merlinorg** [comment]
@obscurerichard my notes for testing sync locally.

```
export DEBUG=true
export SQLALCHEMY_URL=...
export STRAVA_CLIENT_ID=...
export STRAVA_CLIENT_SECRET=...
export VISUAL_CROSSING_API_KEY=...
export START_DATE=2024-11-01T00:00:00-05:00
export END_DATE=2025-03-19T23:59:59-04:00
cd freezing/sync
python3.9 -m cli.sync_activities --athlete-id 12345
python3.9 -m cli.sync_streams --athlete-id 12345
```

I use my own athlete id.

I set the start date to 11/1 so there would be data to pull.

I wind up creating symlinks everywhere to get the latest freezing-model from my local branch.

**Comment by obscurerichard** [comment]
The testing results I had showed that definitely:

1. without the `remove-geo` patches we definitely _do_ have a problem
1. with these, it works
1. The database migrations situation would need to be taken care of
1. I'd still rather do some library upgrades and keep the real geospatial fields in the database
1. We need way better documentation on testing `freezing-sync` but #24 has been open for a _long_ time.
